### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by virengujariya** [twitter/twitter-text#139]
`FATAL EXCEPTION: main
                                                                        Process: me.latergram.latergramme, PID: 7600
                                                                        java.lang.ExceptionInInitializerError
                                                                            at com.twitter.Extractor.extractURLsWithIndices(Extractor.java:297)
                                                                            at com.twitter.Validator.getTweetLength(Validator.java:20)
                                                                            at com.twitter.Validator.isValidTweet(Validator.java:41)`

Above error occurs when caption has url in it. For example,

sample text 1) pugs - Google Search (from https://www.google.ca/search?espv=2&biw=1397&bih=799&tbm=isch&sa=1&q=pugs&oq=pugs&gs_l=img.3...18011.18517.0.18684.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.img..0.0.0.ES9v_NY5YyY#imgrc=ukMLl1cKNvLRLM%3A)

sample text 2) Mashable (from http://mashable.com/) 

I am using api version 1.14.0

**Comment by lbod** [comment]
I don't want to muddy the waters re this issue however, this library blew up as soon as we put it on a Linux server.


**Platform:** Unfortunately we're using Java 6 OpenJDK on an RHEL 5 environment. However we do have an opportunity to switch to oracle Java 7 if this will fix the issue. 

@YutaSakata I tried your patch which got round the `Extractor.extractURLsWithIndices` error however it then blew up at :
Also cc'ing @twuttke 
>>
Caused by: java.lang.ExceptionInInitializerError
        at com.twitter.Extractor.extractMentionsOrListsWithIndices(Extractor.java:219)
        at com.twitter.Extractor.extractEntitiesWithIndices(Extractor.java:158)
        at com.twitter.Autolink.autoLink(Autolink.java:307)
........
Caused by: java.util.regex.PatternSyntaxException: Illegal character range near index 66
(^|[^&\p{L}\p{M}\p{Nd}\u0de6-\u0def\ua9f0-\ua9f9\ud804\udcf0-\ud804\udcf9\ud804\udd36-\ud804\udd3f\ud804\uddd0-\ud804\uddd9\ud804\udef0-\ud804\udef


Which I think is the unicode range ud804??

If this is related to #111 could someone please explain what's actually going on here and whether there's a workaround? i.e. upgrading to java 7, installing extra code pages etc
